name: ci

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: [ '1.22.x', '1.21.x' ]
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Install Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-v1-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run tests
        run: go test -p 1 -v ./...
        env:
          POSTGRES_URL: redis://localhost:6379/0
